### ISSUE TITLE
update to qt5.15 or qt6.x

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input-sdk#42]
Mac and other platforms are slowly moving to it

**Comment by PeterPetrik** [comment]
blocking https://github.com/lutraconsulting/input/issues/1417

**Comment by tomasMizera** [comment]
Qt 5.15.6 updated xCode build system to the new one, see: https://stackoverflow.com/questions/69049200/qt-5-12-for-ios-build-system and the commit: https://codereview.qt-project.org/c/qt/qtbase/+/353118

Currently (with 5.14.2) in order to build iOS, you need to first generate the project (qmake will generate it with legacy build system xCode 10), then open the generated project with xCode and set manually the new build system (https://bugreports.qt.io/browse/QTCREATORBUG-25368?gerritReviewStatus=Open)

What one can do in order to not go to xCode is to remove the two lines from the linked commit (https://codereview.qt-project.org/c/qt/qtbase/+/353118)

**Comment by tomasMizera** [comment]
We need to do this sooner than later, https://bugreports.qt.io/browse/QTBUG-71590 is another issue we face for using 5.14.2 that might lead to updates being blocked

**Comment by PeterPetrik** [comment]
Unfortunately, only open-source version available is 5.15.2, which doesn't have any of these updates. So we will need to go directly to 6.x versions

<img width="169" alt="Screenshot 2021-12-20 at 8 50 19" src="https://user-images.githubusercontent.com/804608/146731466-909e27f3-79cc-44af-8b7b-f82c1fc9c3a3.png">

**Comment by tomasMizera** [comment]
Another nice bug fix that is in 5.15/6.x: https://bugreports.qt.io/browse/QTBUG-82819 <- currently on mac (and probably Linux) we can not read position. Though we are not using it ATM, it might be beneficial for development.

**Comment by PeterPetrik** [comment]
qtkeychain + android needs patch, see https://github.com/frankosterfeld/qtkeychain/pull/196
